---
- name: Install common packages, upgrade if available
  package: name={{ item }} state=latest update_cache=true
  loop: "{{ packages }}"
  tags:
    - packages

- name: Open HTTP port for the webservers
  firewalld: service=http permanent=true state=enabled
  vars:
    ansible_python_interpreter: '/usr/bin/python3'
  tags:
    - webserver_port

- name: Ensure group "Jenkins" exists
  ansible.builtin.group:
    name: jenkins
    state: present
  tags:
    - jenkins_user

- name: Create Jenkins user
  user:
    name: jenkins
    generate_ssh_key: true
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    group: jenkins
  tags:
    - jenkins_user
