---
- hosts: all
  # Become root user
  become: yes
  # List of tasks to be executed
  tasks:
    - name: Remove wget from RHEL like
      become: yes
      yum:
        name: httpd
        state: present
        tags: webserver
    - name: Remove wget from RHEL like
      become: yes
      apt:
        name: httpd
        state: present
        tags: webserver
